---
- name: Install base software
  register: base_software
  become: true
  apt:
    package: "{{ packages }}"
    state: present
    update_cache: yes

- name: Symlink Python3
  when: base_software is success
  become: true
  file: 
    src: /usr/bin/python3
    path: /usr/bin/python
    state: link
