---
- name: Clone local dotfiles
  register: dotfiles_local
  git:
    repo: https://github.com/audibleblink/dotbot.local.git
    dest: ~/.dotfiles.local
    recursive: false

- name: Install local dotfiles
  shell: 
    chdir: ~/.dotfiles.local
    cmd: git checkout Linux && ./install
  when: dotfiles_local is success

- name: Clone dotfiles
  register: dotfiles
  git:
    repo: https://github.com/audibleblink/dotbot.git
    dest: ~/.dotfiles
    recursive: false
  ignore_errors: yes

- name: Install dotfiles
  shell: 
    chdir: ~/.dotfiles
    cmd: ./install
  when: dotfiles is success
  ignore_errors: yes

- name: Install Vim Plugins
  shell: vim +PlugInstall +qa
