- name: Install node version manager
  shell: 
    cmd: "curl -sL {{ nvm_install_url }} | bash -s -- -q"
    creates: ~/n
  ignore_errors: yes

- name: Install golang version manager
  shell: 
    cmd: "curl -s -S -L {{ gvm_install_url }} | bash"
    creates: ~/.gvm

- name: Install rbenv version manager
  git:
    repo: "{{ rbenv_repo }}"
    dest: ~/.rbenv

- name: Install optional dev packages
  become: yes
  apt:
    package: "{{ dev_optional }}"
    state: present
    update_cache: yes
